repos:
  - repo: https://github.com/homebysix/pre-commit-macadmin
    rev: v1.12.3
    hooks:
      - id: check-autopkg-recipes
        args: ["--recipe-prefix=com.github.iancohn.", "--strict", "--"]
      - id: forbid-autopkg-overrides
      - id: forbid-autopkg-trust-info
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=100"]
      - id: check-ast
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: fix-encoding-pragma
      - id: mixed-line-ending
      - id: trailing-whitespace
        args: ["--markdown-linebreak-ext=md"]
  - repo: https://github.com/ambv/black
    rev: 22.8.0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort

  # For future consideration:
  # - repo: https://github.com/pycqa/flake8
  #   rev: 5.0.4
  #   hooks:
  #     - id: flake8
  # - repo: https://github.com/PyCQA/pylint
  #   rev: v2.13.5
  #   hooks:
  #     - id: pylint
